DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS mapping;
DROP TABLE IF EXISTS werte;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE mapping (
    uuid TEXT PRIMARY KEY,
    partei TEXT NOT NULL,
    art TEXT NOT NULL,
    bezug INTEGER NOT NULL
);

CREATE TABLE werte (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uuid TEXT REFERENCES mapping,
    stand TEXT,
    date TEXT
);